version: '3.8'

services:
  sme-service-db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sme_db
    ports:
      - "5432:5432"
    volumes:
      - sme-data:/var/lib/postgresql/data
    networks:
      - sme-network

  emp-service-db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: employee_db
      PGPORT: 5123
    ports:
      - "5123:5123"
    volumes:
      - emp-data:/var/lib/postgresql/data
    networks:
      - sme-network

  redis:
    image: redis:alpine3.17
    restart: always
    ports:
      - "6379:6379"
    networks:
      - sme-network

  sme-service:
    build: .
    image: ahmedbaz/sme-service:1.0
    ports:
      - "9999:9999"
    depends_on:
      - redis
      - sme-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sme-service-db:5432/sme_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING.DATA.REDIS.HOST: redis
      SPRING.DATA.REDIS.PORT: 6379
    networks:
      - sme-network

  employee-service:
    image: ahmedbaz/employee-service:1.0
    ports:
      - "8888:8888"
    depends_on:
      - emp-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://emp-service-db:5123/employee_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - sme-network

volumes:
  sme-data:
  emp-data:
networks:
  sme-network: