scrape_configs:
  - job_name: 'smeMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:9999']
        labels:
          application: 'sme service'