apiVersion: v1
kind: Secret
metadata:
  name: sme-db-secret
type: Opaque
data:
  sme_username: YWRtaW4=
  sme_password: cG9zdGdyZXM=
  emp_username: ZW1wbG95ZWVfc2VydmljZQ==
  emp_password: ZW1wbG95ZWVfc2VydmljZQ==


