apiVersion: v1
kind: Service
metadata:
  name: sme-service
spec:
  selector:
    app: sme-app
  ports:
    - protocol: TCP
      name: sme
      port: 9999
      targetPort: 9999
    - protocol: TCP
      name: eureka
      port: 8761
      targetPort: 8761
    - protocol: TCP
      name: redis
      port: 6379
      targetPort: 6379
    - protocol: TCP
      name: emp
      port: 8888
      targetPort: 8888
  type: NodePort
