package com.sme.app.exception;

public interface AppErrorKeys {

    String GENERAL_ERROR = "GENERAL_ERROR";
    String EMPLOYEE_NOT_FOUND = "EMPLOYEE_NOT_FOUND";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String USER_NOT_ALLOWED = "USER_NOT_ALLOWED";
    String EMAIL_IS_REQUIRED = "EMAIL_IS_REQUIRED";
    String EXIST_EMAIL = "EXIST_EMAIL";
    String NOT_FOUND = "NOT_FOUND";
    String SME_NOT_FOUND = "SME_NOT_FOUND";
    String INTEGRATION_ISSUE = "INTEGRATION_ISSUE";
    String SME_ACCESS_NOT_ALLOWED_WITH_ADMIN = "SME_ACCESS_NOT_ALLOWED_WITH_ADMIN";
    String INVALID_SME = "INVALID_SME";
}
